server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Assets estáticos con cacheo
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|json|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback — cualquier ruta no coincidente va a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}