"""initial_clean_baseline

Revision ID: 0676e55518a7
Revises: 
Create Date: 2026-05-14 08:24:58.288434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0676e55518a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(), nullable=True),
    sa.Column('apellidos', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('preferencia_tema', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('password_hash', sa.TEXT(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('institucion', sa.String(), nullable=True),
    sa.Column('estudia_en', sa.String(), nullable=True),
    sa.Column('tipo_entidad', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('departamento', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('tiktok_url', sa.String(), nullable=True),
    sa.Column('learning_path_url', sa.String(), nullable=True),
    sa.Column('perfil_publico', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.CheckConstraint("rol IN ('ADMIN', 'ORGANIZADOR', 'MODERADOR', 'SOPORTE', 'EMBAJADOR', 'MIEMBRO')", name='usuarios_rol_check'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('anuncios',
    sa.Column('id_anuncio', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('contenido', sa.TEXT(), nullable=True),
    sa.Column('url_imagen', sa.String(), nullable=True),
    sa.Column('link_accion', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_autor'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_anuncio')
    )
    op.create_index(op.f('ix_anuncios_id_anuncio'), 'anuncios', ['id_anuncio'], unique=False)
    op.create_table('auspiciadores',
    sa.Column('id_auspiciador', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('sitio_web', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auspiciador')
    )
    op.create_index(op.f('ix_auspiciadores_id_auspiciador'), 'auspiciadores', ['id_auspiciador'], unique=False)
    op.create_table('comunidades_aliadas',
    sa.Column('id_comunidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('link_contacto', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comunidad')
    )
    op.create_index(op.f('ix_comunidades_aliadas_id_comunidad'), 'comunidades_aliadas', ['id_comunidad'], unique=False)
    op.create_table('configuracion_global',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=True),
    sa.Column('valor', sa.TEXT(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_config'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nombre_curso', sa.String(), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('horas_academicas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('id_instructor', sa.Integer(), nullable=True),
    sa.Column('es_ms_learning', sa.Boolean(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('uid_ms', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_instructor'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_index(op.f('ix_cursos_id_curso'), 'cursos', ['id_curso'], unique=False)
    op.create_table('eventos',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('hora_fin', sa.String(), nullable=True),
    sa.Column('modalidad', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('capacidad_max', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('token_qr', sa.String(), nullable=True),
    sa.Column('id_organizador', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_organizador'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_eventos_id_evento'), 'eventos', ['id_evento'], unique=False)
    op.create_table('logs_sistema',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('tabla_afectada', sa.String(), nullable=True),
    sa.Column('id_registro_afectado', sa.Integer(), nullable=True),
    sa.Column('valor_anterior', sa.TEXT(), nullable=True),
    sa.Column('valor_nuevo', sa.TEXT(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('ip_direccion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_logs_sistema_id_log'), 'logs_sistema', ['id_log'], unique=False)
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('estado_pago', sa.String(), nullable=True),
    sa.Column('comprobante_url', sa.TEXT(), nullable=True),
    sa.Column('id_referencia', sa.Integer(), nullable=True),
    sa.Column('tipo_referencia', sa.String(), nullable=True),
    sa.Column('validado_por', sa.Integer(), nullable=True),
    sa.Column('url_comprobante', sa.String(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('notas_admin', sa.TEXT(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pagos_id_pago'), 'pagos', ['id_pago'], unique=False)
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('es_kit_evento', sa.Boolean(), nullable=True),
    sa.Column('imagen_url', sa.TEXT(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_productos_id_producto'), 'productos', ['id_producto'], unique=False)
    op.create_table('speakers',
    sa.Column('id_speaker', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('trayectoria', sa.TEXT(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('trabajo_actual', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_speaker')
    )
    op.create_index(op.f('ix_speakers_id_speaker'), 'speakers', ['id_speaker'], unique=False)
    op.create_table('badges',
    sa.Column('id_badge', sa.Integer(), nullable=False),
    sa.Column('nombre_badge', sa.String(), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('imagen_url', sa.TEXT(), nullable=True),
    sa.Column('id_evento_origen', sa.Integer(), nullable=True),
    sa.Column('id_curso_origen', sa.Integer(), nullable=True),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('requisito_nivel', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_curso_origen'], ['cursos.id_curso'], ),
    sa.ForeignKeyConstraint(['id_evento_origen'], ['eventos.id_evento'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_badge')
    )
    op.create_index(op.f('ix_badges_id_badge'), 'badges', ['id_badge'], unique=False)
    op.create_table('certificados',
    sa.Column('id_certificado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('uuid_verificacion', sa.String(), nullable=True),
    sa.Column('codigo_verificacion', sa.String(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('url_pdf', sa.String(), nullable=True),
    sa.Column('formato', sa.String(), nullable=True),
    sa.Column('entregado_fisico', sa.Boolean(), nullable=True),
    sa.Column('es_ruta_linkedin', sa.Boolean(), nullable=True),
    sa.Column('metadata_adicional', sa.TEXT(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.CheckConstraint("formato IN ('DIGITAL', 'FISICO', 'AMBOS')", name='certificados_formato_check'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_certificado'),
    sa.UniqueConstraint('codigo_verificacion'),
    sa.UniqueConstraint('uuid_verificacion')
    )
    op.create_index(op.f('ix_certificados_id_certificado'), 'certificados', ['id_certificado'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id_checkpoint', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('nombre_checkpoint', sa.String(), nullable=True),
    sa.Column('hora_apertura', sa.DateTime(), nullable=True),
    sa.Column('hora_cierre', sa.DateTime(), nullable=True),
    sa.Column('tipo_checkpoint', sa.String(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_checkpoint')
    )
    op.create_index(op.f('ix_checkpoints_id_checkpoint'), 'checkpoints', ['id_checkpoint'], unique=False)
    op.create_table('eventos_auspiciadores',
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_auspiciador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_auspiciador'], ['auspiciadores.id_auspiciador'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ondelete='CASCADE')
    )
    op.create_table('eventos_comunidades',
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_comunidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comunidad'], ['comunidades_aliadas.id_comunidad'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ondelete='CASCADE')
    )
    op.create_table('eventos_speakers',
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_speaker', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_speaker'], ['speakers.id_speaker'], ondelete='CASCADE')
    )
    op.create_table('inscripciones_cursos',
    sa.Column('id_inscripcion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('progreso_porcentaje', sa.Integer(), nullable=True),
    sa.Column('nota_final', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=True),
    sa.Column('id_pago', sa.Integer(), nullable=True),
    sa.Column('estado_inscripcion', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id_pago'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_inscripcion')
    )
    op.create_index(op.f('ix_inscripciones_cursos_id_inscripcion'), 'inscripciones_cursos', ['id_inscripcion'], unique=False)
    op.create_table('inscripciones_eventos',
    sa.Column('id_inscripcion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.Column('estado_inscripcion', sa.String(), nullable=True),
    sa.Column('codigo_qr', sa.String(), nullable=True),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('id_pago', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id_pago'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_inscripcion'),
    sa.UniqueConstraint('codigo_qr')
    )
    op.create_index(op.f('ix_inscripciones_eventos_id_inscripcion'), 'inscripciones_eventos', ['id_inscripcion'], unique=False)
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_pago', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id_pago'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_index(op.f('ix_pedidos_id_pedido'), 'pedidos', ['id_pedido'], unique=False)
    op.create_table('recursos',
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('url_descarga', sa.String(), nullable=True),
    sa.Column('tipo_archivo', sa.String(), nullable=True),
    sa.Column('tipo_recurso', sa.String(), nullable=True),
    sa.Column('contenido_md', sa.TEXT(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recurso')
    )
    op.create_index(op.f('ix_recursos_id_recurso'), 'recursos', ['id_recurso'], unique=False)
    op.create_table('asistencia_detalles',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_inscripcion', sa.Integer(), nullable=True),
    sa.Column('id_checkpoint', sa.Integer(), nullable=True),
    sa.Column('fecha_escaneo', sa.DateTime(), nullable=True),
    sa.Column('escanedao_por', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['escanedao_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_checkpoint'], ['checkpoints.id_checkpoint'], ),
    sa.ForeignKeyConstraint(['id_inscripcion'], ['inscripciones_eventos.id_inscripcion'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_index(op.f('ix_asistencia_detalles_id_asistencia'), 'asistencia_detalles', ['id_asistencia'], unique=False)
    op.create_table('pedido_detalles',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_pedido_detalles_id_detalle'), 'pedido_detalles', ['id_detalle'], unique=False)
    op.create_table('usuarios_badges',
    sa.Column('id_usuario_badge', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_badge', sa.Integer(), nullable=True),
    sa.Column('fecha_obtencion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_badge'], ['badges.id_badge'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_badge')
    )
    op.create_index(op.f('ix_usuarios_badges_id_usuario_badge'), 'usuarios_badges', ['id_usuario_badge'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_badges_id_usuario_badge'), table_name='usuarios_badges')
    op.drop_table('usuarios_badges')
    op.drop_index(op.f('ix_pedido_detalles_id_detalle'), table_name='pedido_detalles')
    op.drop_table('pedido_detalles')
    op.drop_index(op.f('ix_asistencia_detalles_id_asistencia'), table_name='asistencia_detalles')
    op.drop_table('asistencia_detalles')
    op.drop_index(op.f('ix_recursos_id_recurso'), table_name='recursos')
    op.drop_table('recursos')
    op.drop_index(op.f('ix_pedidos_id_pedido'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_inscripciones_eventos_id_inscripcion'), table_name='inscripciones_eventos')
    op.drop_table('inscripciones_eventos')
    op.drop_index(op.f('ix_inscripciones_cursos_id_inscripcion'), table_name='inscripciones_cursos')
    op.drop_table('inscripciones_cursos')
    op.drop_table('eventos_speakers')
    op.drop_table('eventos_comunidades')
    op.drop_table('eventos_auspiciadores')
    op.drop_index(op.f('ix_checkpoints_id_checkpoint'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_certificados_id_certificado'), table_name='certificados')
    op.drop_table('certificados')
    op.drop_index(op.f('ix_badges_id_badge'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_speakers_id_speaker'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_productos_id_producto'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_pagos_id_pago'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_logs_sistema_id_log'), table_name='logs_sistema')
    op.drop_table('logs_sistema')
    op.drop_index(op.f('ix_eventos_id_evento'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_cursos_id_curso'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_table('configuracion_global')
    op.drop_index(op.f('ix_comunidades_aliadas_id_comunidad'), table_name='comunidades_aliadas')
    op.drop_table('comunidades_aliadas')
    op.drop_index(op.f('ix_auspiciadores_id_auspiciador'), table_name='auspiciadores')
    op.drop_table('auspiciadores')
    op.drop_index(op.f('ix_anuncios_id_anuncio'), table_name='anuncios')
    op.drop_table('anuncios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
