"""add_speaker_social_fields

Revision ID: 176e2e42d2cb
Revises: fbe03e1faad8
Create Date: 2026-05-18 21:26:11.823355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176e2e42d2cb'
down_revision: Union[str, Sequence[str], None] = 'fbe03e1faad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('speakers', sa.Column('instagram_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'instagram_url')
    op.drop_column('speakers', 'facebook_url')
    # ### end Alembic commands ###
