"""expand_recurso_model

Revision ID: 19edfe311d60
Revises: 46f3ac215fad
Create Date: 2026-05-19 00:31:34.794284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19edfe311d60'
down_revision: Union[str, Sequence[str], None] = '46f3ac215fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recursos', sa.Column('motivo', sa.String(), nullable=True))
    op.add_column('recursos', sa.Column('autor_nombre', sa.String(), nullable=True))
    op.add_column('recursos', sa.Column('id_evento', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recursos', 'eventos', ['id_evento'], ['id_evento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recursos', type_='foreignkey')
    op.drop_column('recursos', 'id_evento')
    op.drop_column('recursos', 'autor_nombre')
    op.drop_column('recursos', 'motivo')
    # ### end Alembic commands ###
