"""add_contact_fields_to_ecosystem

Revision ID: 46f3ac215fad
Revises: 176e2e42d2cb
Create Date: 2026-05-18 22:49:47.050997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f3ac215fad'
down_revision: Union[str, Sequence[str], None] = '176e2e42d2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auspiciadores', sa.Column('correo_contacto', sa.String(), nullable=True))
    op.add_column('auspiciadores', sa.Column('whatsapp_contacto', sa.String(), nullable=True))
    op.add_column('comunidades_aliadas', sa.Column('correo_contacto', sa.String(), nullable=True))
    op.add_column('comunidades_aliadas', sa.Column('whatsapp_contacto', sa.String(), nullable=True))
    op.add_column('speakers', sa.Column('correo_contacto', sa.String(), nullable=True))
    op.add_column('speakers', sa.Column('whatsapp_contacto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'whatsapp_contacto')
    op.drop_column('speakers', 'correo_contacto')
    op.drop_column('comunidades_aliadas', 'whatsapp_contacto')
    op.drop_column('comunidades_aliadas', 'correo_contacto')
    op.drop_column('auspiciadores', 'whatsapp_contacto')
    op.drop_column('auspiciadores', 'correo_contacto')
    # ### end Alembic commands ###
