"""create_academia_lms_tables

Revision ID: 5d648885e1d4
Revises: 8b9b66e59fb9
Create Date: 2026-05-19 00:52:10.476847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d648885e1d4'
down_revision: Union[str, Sequence[str], None] = '8b9b66e59fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecciones',
    sa.Column('id_leccion', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('contenido_video_url', sa.String(), nullable=True),
    sa.Column('contenido_texto', sa.TEXT(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_leccion')
    )
    op.create_index(op.f('ix_lecciones_id_leccion'), 'lecciones', ['id_leccion'], unique=False)
    op.create_table('posts_foro',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.TEXT(), nullable=True),
    sa.Column('es_pregunta_docente', sa.Boolean(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_index(op.f('ix_posts_foro_id_post'), 'posts_foro', ['id_post'], unique=False)
    op.create_table('tareas',
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('id_leccion', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('instrucciones', sa.TEXT(), nullable=True),
    sa.Column('puntos_max', sa.Integer(), nullable=True),
    sa.Column('fecha_entrega_limite', sa.DateTime(), nullable=True),
    sa.Column('archivo_adjunto_url', sa.String(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_leccion'], ['lecciones.id_leccion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    op.create_index(op.f('ix_tareas_id_tarea'), 'tareas', ['id_tarea'], unique=False)
    op.create_table('entregas_tareas',
    sa.Column('id_entrega', sa.Integer(), nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('archivo_url', sa.String(), nullable=True),
    sa.Column('comentario_alumno', sa.TEXT(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('comentario_docente', sa.TEXT(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tareas.id_tarea'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_entrega')
    )
    op.create_index(op.f('ix_entregas_tareas_id_entrega'), 'entregas_tareas', ['id_entrega'], unique=False)
    op.add_column('cursos', sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'costo')
    op.drop_index(op.f('ix_entregas_tareas_id_entrega'), table_name='entregas_tareas')
    op.drop_table('entregas_tareas')
    op.drop_index(op.f('ix_tareas_id_tarea'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_posts_foro_id_post'), table_name='posts_foro')
    op.drop_table('posts_foro')
    op.drop_index(op.f('ix_lecciones_id_leccion'), table_name='lecciones')
    op.drop_table('lecciones')
    # ### end Alembic commands ###
