"""sincronizar_audit_y_relaciones

Revision ID: 85992305f424
Revises: 6ca3ebfeb88a
Create Date: 2026-05-11 16:06:25.620491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85992305f424'
down_revision: Union[str, Sequence[str], None] = '6ca3ebfeb88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_badges')
    op.drop_table('pedidos_detalle')
    op.drop_table('productos')
    op.drop_table('badges')
    op.drop_table('asistencias_detalle')
    op.drop_table('pedidos')
    op.alter_column('anuncios', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('anuncios', 'contenido',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('anuncios_id_autor_fkey'), 'anuncios', type_='foreignkey')
    op.drop_column('anuncios', 'id_autor')
    op.add_column('asistencia_detalles', sa.Column('creado_por', sa.Integer(), nullable=True))
    op.add_column('asistencia_detalles', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('asistencia_detalles', sa.Column('modificado_por', sa.Integer(), nullable=True))
    op.add_column('asistencia_detalles', sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'asistencia_detalles', 'usuarios', ['modificado_por'], ['id_usuario'])
    op.create_foreign_key(None, 'asistencia_detalles', 'usuarios', ['creado_por'], ['id_usuario'])
    op.alter_column('certificados', 'codigo_verificacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('certificados', 'fecha_emision',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('certificados', 'url_pdf',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_certificados_id_certificado'), 'certificados', ['id_certificado'], unique=False)
    op.drop_constraint(op.f('certificados_id_usuario_fkey'), 'certificados', type_='foreignkey')
    op.create_foreign_key(None, 'certificados', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.drop_column('certificados', 'entregado_fisico')
    op.add_column('checkpoints', sa.Column('orden', sa.Integer(), nullable=True))
    op.add_column('checkpoints', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('checkpoints', sa.Column('creado_por', sa.Integer(), nullable=True))
    op.add_column('checkpoints', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('checkpoints', sa.Column('modificado_por', sa.Integer(), nullable=True))
    op.add_column('checkpoints', sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
    op.alter_column('checkpoints', 'nombre_checkpoint',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_checkpoints_id_checkpoint'), 'checkpoints', ['id_checkpoint'], unique=False)
    op.drop_constraint(op.f('checkpoints_id_evento_fkey'), 'checkpoints', type_='foreignkey')
    op.create_foreign_key(None, 'checkpoints', 'eventos', ['id_evento'], ['id_evento'])
    op.create_foreign_key(None, 'checkpoints', 'usuarios', ['modificado_por'], ['id_usuario'])
    op.create_foreign_key(None, 'checkpoints', 'usuarios', ['creado_por'], ['id_usuario'])
    op.drop_column('checkpoints', 'tipo_checkpoint')
    op.drop_column('checkpoints', 'hora_cierre')
    op.drop_column('checkpoints', 'hora_apertura')
    op.alter_column('cursos', 'nombre_curso',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cursos', 'horas_academicas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_cursos_id_curso'), 'cursos', ['id_curso'], unique=False)
    op.drop_constraint(op.f('cursos_id_instructor_fkey'), 'cursos', type_='foreignkey')
    op.create_foreign_key(None, 'cursos', 'usuarios', ['id_instructor'], ['id_usuario'])
    op.alter_column('eventos', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('eventos', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('eventos', 'capacidad_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('eventos_token_qr_key'), 'eventos', type_='unique')
    op.create_index(op.f('ix_eventos_id_evento'), 'eventos', ['id_evento'], unique=False)
    op.add_column('inscripciones_cursos', sa.Column('id_inscripcion_curso', sa.Integer(), nullable=False))
    op.add_column('inscripciones_cursos', sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('progreso', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('nota_final', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('completado', sa.Boolean(), nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('fecha_completado', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('inscripciones_cursos_id_usuario_id_curso_key'), 'inscripciones_cursos', type_='unique')
    op.create_index(op.f('ix_inscripciones_cursos_id_inscripcion_curso'), 'inscripciones_cursos', ['id_inscripcion_curso'], unique=False)
    op.drop_constraint(op.f('inscripciones_cursos_id_pago_fkey'), 'inscripciones_cursos', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_cursos_id_usuario_fkey'), 'inscripciones_cursos', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_cursos_id_curso_fkey'), 'inscripciones_cursos', type_='foreignkey')
    op.create_foreign_key(None, 'inscripciones_cursos', 'cursos', ['id_curso'], ['id_curso'])
    op.create_foreign_key(None, 'inscripciones_cursos', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.drop_column('inscripciones_cursos', 'estado_inscripcion')
    op.drop_column('inscripciones_cursos', 'id_inscripcion')
    op.drop_column('inscripciones_cursos', 'finalizado')
    op.drop_column('inscripciones_cursos', 'id_pago')
    op.drop_column('inscripciones_cursos', 'progreso_porcentaje')
    op.add_column('inscripciones_eventos', sa.Column('codigo_qr', sa.String(), nullable=True))
    op.drop_constraint(op.f('inscripciones_eventos_id_usuario_id_evento_key'), 'inscripciones_eventos', type_='unique')
    op.create_index(op.f('ix_inscripciones_eventos_id_inscripcion'), 'inscripciones_eventos', ['id_inscripcion'], unique=False)
    op.create_unique_constraint(None, 'inscripciones_eventos', ['codigo_qr'])
    op.drop_constraint(op.f('inscripciones_eventos_id_usuario_fkey'), 'inscripciones_eventos', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_eventos_id_pago_fkey'), 'inscripciones_eventos', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_eventos_id_evento_fkey'), 'inscripciones_eventos', type_='foreignkey')
    op.create_foreign_key(None, 'inscripciones_eventos', 'eventos', ['id_evento'], ['id_evento'])
    op.create_foreign_key(None, 'inscripciones_eventos', 'pagos', ['id_pago'], ['id_pago'])
    op.create_foreign_key(None, 'inscripciones_eventos', 'usuarios', ['id_usuario'], ['id_usuario'])
    op.alter_column('logs_sistema', 'accion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_logs_sistema_id_log'), 'logs_sistema', ['id_log'], unique=False)
    op.alter_column('pagos', 'monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_pagos_id_pago'), 'pagos', ['id_pago'], unique=False)
    op.drop_column('pagos', 'comprobante_url')
    op.add_column('recursos', sa.Column('modificado_por', sa.Integer(), nullable=True))
    op.add_column('recursos', sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'recursos', 'usuarios', ['modificado_por'], ['id_usuario'])
    op.add_column('usuarios', sa.Column('alias', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('foto_url', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('preferencia_tema', sa.String(), nullable=True))
    op.alter_column('usuarios', 'nombres',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuarios', 'apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('usuarios_correo_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_correo_key'), 'usuarios', ['correo'], postgresql_nulls_not_distinct=False)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('usuarios', 'apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'nombres',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('usuarios', 'preferencia_tema')
    op.drop_column('usuarios', 'foto_url')
    op.drop_column('usuarios', 'alias')
    op.drop_constraint(None, 'recursos', type_='foreignkey')
    op.drop_column('recursos', 'fecha_modificacion')
    op.drop_column('recursos', 'modificado_por')
    op.add_column('pagos', sa.Column('comprobante_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pagos_id_pago'), table_name='pagos')
    op.alter_column('pagos', 'monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_logs_sistema_id_log'), table_name='logs_sistema')
    op.alter_column('logs_sistema', 'accion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'inscripciones_eventos', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones_eventos', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones_eventos', type_='foreignkey')
    op.create_foreign_key(op.f('inscripciones_eventos_id_evento_fkey'), 'inscripciones_eventos', 'eventos', ['id_evento'], ['id_evento'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inscripciones_eventos_id_pago_fkey'), 'inscripciones_eventos', 'pagos', ['id_pago'], ['id_pago'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inscripciones_eventos_id_usuario_fkey'), 'inscripciones_eventos', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
    op.drop_constraint(None, 'inscripciones_eventos', type_='unique')
    op.drop_index(op.f('ix_inscripciones_eventos_id_inscripcion'), table_name='inscripciones_eventos')
    op.create_unique_constraint(op.f('inscripciones_eventos_id_usuario_id_evento_key'), 'inscripciones_eventos', ['id_usuario', 'id_evento'], postgresql_nulls_not_distinct=False)
    op.drop_column('inscripciones_eventos', 'codigo_qr')
    op.add_column('inscripciones_cursos', sa.Column('progreso_porcentaje', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('id_pago', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('finalizado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('inscripciones_cursos', sa.Column('id_inscripcion', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('inscripciones_cursos', sa.Column('estado_inscripcion', sa.VARCHAR(length=20), server_default=sa.text("'PENDIENTE'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inscripciones_cursos', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones_cursos', type_='foreignkey')
    op.create_foreign_key(op.f('inscripciones_cursos_id_curso_fkey'), 'inscripciones_cursos', 'cursos', ['id_curso'], ['id_curso'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inscripciones_cursos_id_usuario_fkey'), 'inscripciones_cursos', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inscripciones_cursos_id_pago_fkey'), 'inscripciones_cursos', 'pagos', ['id_pago'], ['id_pago'], ondelete='SET NULL')
    op.drop_index(op.f('ix_inscripciones_cursos_id_inscripcion_curso'), table_name='inscripciones_cursos')
    op.create_unique_constraint(op.f('inscripciones_cursos_id_usuario_id_curso_key'), 'inscripciones_cursos', ['id_usuario', 'id_curso'], postgresql_nulls_not_distinct=False)
    op.drop_column('inscripciones_cursos', 'fecha_completado')
    op.drop_column('inscripciones_cursos', 'completado')
    op.drop_column('inscripciones_cursos', 'nota_final')
    op.drop_column('inscripciones_cursos', 'progreso')
    op.drop_column('inscripciones_cursos', 'fecha_inscripcion')
    op.drop_column('inscripciones_cursos', 'id_inscripcion_curso')
    op.drop_index(op.f('ix_eventos_id_evento'), table_name='eventos')
    op.create_unique_constraint(op.f('eventos_token_qr_key'), 'eventos', ['token_qr'], postgresql_nulls_not_distinct=False)
    op.alter_column('eventos', 'capacidad_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('eventos', 'fecha_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('eventos', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint(None, 'cursos', type_='foreignkey')
    op.create_foreign_key(op.f('cursos_id_instructor_fkey'), 'cursos', 'usuarios', ['id_instructor'], ['id_usuario'], ondelete='SET NULL')
    op.drop_index(op.f('ix_cursos_id_curso'), table_name='cursos')
    op.alter_column('cursos', 'horas_academicas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cursos', 'nombre_curso',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('checkpoints', sa.Column('hora_apertura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('checkpoints', sa.Column('hora_cierre', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('checkpoints', sa.Column('tipo_checkpoint', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.create_foreign_key(op.f('checkpoints_id_evento_fkey'), 'checkpoints', 'eventos', ['id_evento'], ['id_evento'], ondelete='CASCADE')
    op.drop_index(op.f('ix_checkpoints_id_checkpoint'), table_name='checkpoints')
    op.alter_column('checkpoints', 'nombre_checkpoint',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('checkpoints', 'fecha_modificacion')
    op.drop_column('checkpoints', 'modificado_por')
    op.drop_column('checkpoints', 'fecha_creacion')
    op.drop_column('checkpoints', 'creado_por')
    op.drop_column('checkpoints', 'activo')
    op.drop_column('checkpoints', 'orden')
    op.add_column('certificados', sa.Column('entregado_fisico', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'certificados', type_='foreignkey')
    op.create_foreign_key(op.f('certificados_id_usuario_fkey'), 'certificados', 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
    op.drop_index(op.f('ix_certificados_id_certificado'), table_name='certificados')
    op.alter_column('certificados', 'url_pdf',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('certificados', 'fecha_emision',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('certificados', 'codigo_verificacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'asistencia_detalles', type_='foreignkey')
    op.drop_constraint(None, 'asistencia_detalles', type_='foreignkey')
    op.drop_column('asistencia_detalles', 'fecha_modificacion')
    op.drop_column('asistencia_detalles', 'modificado_por')
    op.drop_column('asistencia_detalles', 'fecha_creacion')
    op.drop_column('asistencia_detalles', 'creado_por')
    op.add_column('anuncios', sa.Column('id_autor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('anuncios_id_autor_fkey'), 'anuncios', 'usuarios', ['id_autor'], ['id_usuario'])
    op.alter_column('anuncios', 'contenido',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('anuncios', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_pago', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado_entrega', sa.VARCHAR(length=20), server_default=sa.text("'PENDIENTE'::character varying"), autoincrement=False, nullable=True),
    sa.Column('fecha_pedido', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos.id_pago'], name=op.f('pedidos_id_pago_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('pedidos_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id_pedido', name=op.f('pedidos_pkey'))
    )
    op.create_table('asistencias_detalle',
    sa.Column('id_asistencia_det', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_checkpoint', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_escaneo', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_checkpoint'], ['checkpoints.id_checkpoint'], name=op.f('asistencias_detalle_id_checkpoint_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('asistencias_detalle_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id_asistencia_det', name=op.f('asistencias_detalle_pkey'))
    )
    op.create_table('badges',
    sa.Column('id_badge', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_badge', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imagen_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_evento_origen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_curso_origen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_curso_origen'], ['cursos.id_curso'], name=op.f('badges_id_curso_origen_fkey')),
    sa.ForeignKeyConstraint(['id_evento_origen'], ['eventos.id_evento'], name=op.f('badges_id_evento_origen_fkey')),
    sa.PrimaryKeyConstraint('id_badge', name=op.f('badges_pkey'))
    )
    op.create_table('pedidos_detalle',
    sa.Column('id_detalle', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], name=op.f('pedidos_detalle_id_pedido_fkey')),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name=op.f('pedidos_detalle_id_producto_fkey')),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('pedidos_detalle_pkey'))
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('es_kit_evento', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('imagen_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modificado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], name=op.f('productos_modificado_por_fkey')),
    sa.PrimaryKeyConstraint('id_producto', name=op.f('productos_pkey'))
    )
    op.create_table('usuarios_badges',
    sa.Column('id_usuario_badge', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_badge', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_obtencion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_badge'], ['badges.id_badge'], name=op.f('usuarios_badges_id_badge_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('usuarios_badges_id_usuario_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario_badge', name=op.f('usuarios_badges_pkey'))
    )
    # ### end Alembic commands ###
