"""add_portada_to_recurso

Revision ID: 8b9b66e59fb9
Revises: 19edfe311d60
Create Date: 2026-05-19 00:40:08.261720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9b66e59fb9'
down_revision: Union[str, Sequence[str], None] = '19edfe311d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recursos', sa.Column('portada_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recursos', 'portada_url')
    # ### end Alembic commands ###
