"""add_user_security_flags

Revision ID: 8fdf69b6f875
Revises: b4aeb44856a7
Create Date: 2026-05-20 00:10:36.095883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdf69b6f875'
down_revision: Union[str, Sequence[str], None] = 'b4aeb44856a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'costo')
    op.add_column('usuarios', sa.Column('es_nuevo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_exp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'reset_token_exp')
    op.drop_column('usuarios', 'reset_token')
    op.drop_column('usuarios', 'es_nuevo')
    op.add_column('cursos', sa.Column('costo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
