"""add_event_advanced_fields

Revision ID: b4aeb44856a7
Revises: 5d648885e1d4
Create Date: 2026-05-19 00:54:02.784937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aeb44856a7'
down_revision: Union[str, Sequence[str], None] = '5d648885e1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('tipo_evento', sa.String(), nullable=True))
    op.add_column('eventos', sa.Column('refrigerio_incluido', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'refrigerio_incluido')
    op.drop_column('eventos', 'tipo_evento')
    # ### end Alembic commands ###
