"""Add OCR fields to Pago

Revision ID: ce9d3042e36f
Revises: e4c9a71b3d2d
Create Date: 2026-05-21 04:57:48.179214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9d3042e36f'
down_revision: Union[str, Sequence[str], None] = 'e4c9a71b3d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagos', sa.Column('porcentaje_ocr', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pagos', sa.Column('texto_ocr', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagos', 'texto_ocr')
    op.drop_column('pagos', 'porcentaje_ocr')
    # ### end Alembic commands ###
