"""add_event_payment_qrs

Revision ID: d2f530fc2803
Revises: ce9d3042e36f
Create Date: 2026-06-09 21:20:36.288010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f530fc2803'
down_revision: Union[str, Sequence[str], None] = 'ce9d3042e36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_pagos_qr',
    sa.Column('id_qr', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('nombre_paquete', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('url_qr', sa.String(length=255), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('fecha_modificacion_estado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_estado'], ['estados_registro.id_estado'], ),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_qr')
    )
    op.create_index(op.f('ix_eventos_pagos_qr_id_evento'), 'eventos_pagos_qr', ['id_evento'], unique=False)
    op.create_index(op.f('ix_eventos_pagos_qr_id_qr'), 'eventos_pagos_qr', ['id_qr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_pagos_qr_id_qr'), table_name='eventos_pagos_qr')
    op.drop_index(op.f('ix_eventos_pagos_qr_id_evento'), table_name='eventos_pagos_qr')
    op.drop_table('eventos_pagos_qr')
    # ### end Alembic commands ###
