"""fix_schema_typos_and_constraints

Revision ID: fbe03e1faad8
Revises: 0676e55518a7
Create Date: 2026-05-18 15:50:18.239455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe03e1faad8'
down_revision: Union[str, Sequence[str], None] = '0676e55518a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencia_detalles', sa.Column('escaneado_por', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_asistencia_detalles_escaneado_por'), 'asistencia_detalles', ['escaneado_por'], unique=False)
    op.create_index(op.f('ix_asistencia_detalles_id_checkpoint'), 'asistencia_detalles', ['id_checkpoint'], unique=False)
    op.create_index(op.f('ix_asistencia_detalles_id_inscripcion'), 'asistencia_detalles', ['id_inscripcion'], unique=False)
    op.drop_constraint(op.f('asistencia_detalles_escanedao_por_fkey'), 'asistencia_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'asistencia_detalles', 'usuarios', ['escaneado_por'], ['id_usuario'])
    op.drop_column('asistencia_detalles', 'escanedao_por')
    op.create_index(op.f('ix_checkpoints_id_evento'), 'checkpoints', ['id_evento'], unique=False)
    op.create_index(op.f('ix_cursos_id_instructor'), 'cursos', ['id_instructor'], unique=False)
    op.create_index(op.f('ix_eventos_id_organizador'), 'eventos', ['id_organizador'], unique=False)
    op.add_column('inscripciones_cursos', sa.Column('id_inscripcion_curso', sa.Integer(), nullable=False))
    op.add_column('inscripciones_cursos', sa.Column('progreso', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_inscripciones_cursos_id_inscripcion'), table_name='inscripciones_cursos')
    op.create_index(op.f('ix_inscripciones_cursos_id_curso'), 'inscripciones_cursos', ['id_curso'], unique=False)
    op.create_index(op.f('ix_inscripciones_cursos_id_inscripcion_curso'), 'inscripciones_cursos', ['id_inscripcion_curso'], unique=False)
    op.create_index(op.f('ix_inscripciones_cursos_id_pago'), 'inscripciones_cursos', ['id_pago'], unique=False)
    op.create_index(op.f('ix_inscripciones_cursos_id_usuario'), 'inscripciones_cursos', ['id_usuario'], unique=False)
    op.drop_column('inscripciones_cursos', 'progreso_porcentaje')
    op.drop_column('inscripciones_cursos', 'id_inscripcion')
    op.create_index(op.f('ix_inscripciones_eventos_id_evento'), 'inscripciones_eventos', ['id_evento'], unique=False)
    op.create_index(op.f('ix_inscripciones_eventos_id_pago'), 'inscripciones_eventos', ['id_pago'], unique=False)
    op.create_index(op.f('ix_inscripciones_eventos_id_usuario'), 'inscripciones_eventos', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_pagos_id_usuario'), 'pagos', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_pagos_validado_por'), 'pagos', ['validado_por'], unique=False)
    op.create_index(op.f('ix_pedido_detalles_id_pedido'), 'pedido_detalles', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_pedido_detalles_id_producto'), 'pedido_detalles', ['id_producto'], unique=False)
    op.drop_constraint(op.f('pedido_detalles_id_pedido_fkey'), 'pedido_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'pedido_detalles', 'pedidos', ['id_pedido'], ['id_pedido'], ondelete='CASCADE')
    op.create_index(op.f('ix_pedidos_id_pago'), 'pedidos', ['id_pago'], unique=False)
    op.create_index(op.f('ix_pedidos_id_usuario'), 'pedidos', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_id_usuario'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id_pago'), table_name='pedidos')
    op.drop_constraint(None, 'pedido_detalles', type_='foreignkey')
    op.create_foreign_key(op.f('pedido_detalles_id_pedido_fkey'), 'pedido_detalles', 'pedidos', ['id_pedido'], ['id_pedido'])
    op.drop_index(op.f('ix_pedido_detalles_id_producto'), table_name='pedido_detalles')
    op.drop_index(op.f('ix_pedido_detalles_id_pedido'), table_name='pedido_detalles')
    op.drop_index(op.f('ix_pagos_validado_por'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_usuario'), table_name='pagos')
    op.drop_index(op.f('ix_inscripciones_eventos_id_usuario'), table_name='inscripciones_eventos')
    op.drop_index(op.f('ix_inscripciones_eventos_id_pago'), table_name='inscripciones_eventos')
    op.drop_index(op.f('ix_inscripciones_eventos_id_evento'), table_name='inscripciones_eventos')
    op.add_column('inscripciones_cursos', sa.Column('id_inscripcion', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('inscripciones_cursos', sa.Column('progreso_porcentaje', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inscripciones_cursos_id_usuario'), table_name='inscripciones_cursos')
    op.drop_index(op.f('ix_inscripciones_cursos_id_pago'), table_name='inscripciones_cursos')
    op.drop_index(op.f('ix_inscripciones_cursos_id_inscripcion_curso'), table_name='inscripciones_cursos')
    op.drop_index(op.f('ix_inscripciones_cursos_id_curso'), table_name='inscripciones_cursos')
    op.create_index(op.f('ix_inscripciones_cursos_id_inscripcion'), 'inscripciones_cursos', ['id_inscripcion'], unique=False)
    op.drop_column('inscripciones_cursos', 'progreso')
    op.drop_column('inscripciones_cursos', 'id_inscripcion_curso')
    op.drop_index(op.f('ix_eventos_id_organizador'), table_name='eventos')
    op.drop_index(op.f('ix_cursos_id_instructor'), table_name='cursos')
    op.drop_index(op.f('ix_checkpoints_id_evento'), table_name='checkpoints')
    op.add_column('asistencia_detalles', sa.Column('escanedao_por', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asistencia_detalles', type_='foreignkey')
    op.create_foreign_key(op.f('asistencia_detalles_escanedao_por_fkey'), 'asistencia_detalles', 'usuarios', ['escanedao_por'], ['id_usuario'])
    op.drop_index(op.f('ix_asistencia_detalles_id_inscripcion'), table_name='asistencia_detalles')
    op.drop_index(op.f('ix_asistencia_detalles_id_checkpoint'), table_name='asistencia_detalles')
    op.drop_index(op.f('ix_asistencia_detalles_escaneado_por'), table_name='asistencia_detalles')
    op.drop_column('asistencia_detalles', 'escaneado_por')
    # ### end Alembic commands ###
